databases:
  - name: apps_jugoya_ai_db
    plan: free
    databaseName: apps_jugoya_ai
    user: apps_jugoya_ai

services:
  - type: web
    plan: free
    name: apps_jugoya_ai
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn main.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apps_jugoya_ai_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
